app:
  jwtExpirationInMs: '604800000'
  jwtSecret: JWTSuperSecretKey
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
server:
  port: '8086'
spring:
  ldap:
    embedded:
      base-dn: dc=innovativeintelli,dc=com
      ldif: classpath:localldapactivedirectory.ldif
      port: 12345
      validation:
        enabled: false
